version: "3"
services: 
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
      - ./initsql/init.sql:/docker-entrypoint-initdb.d/init.sql